name: helloGithubAction 

on: [push]

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
    #run 뒤에 실제 작동하는 코드를 넣기 .
    - uses: actions/checkout@v2
    
    - name: 1. 파일 록 출력
      run: ls
    - name: 2. 파이썬 실행
      run: python test.py
   
